### ISSUE TITLE
Refresh in IDL Repository does not work

### ISSUE THREAD

**Issue by tandersoft** [RedhawkSDR/eclipse-gov.redhawk.ide#10]
There is a right click menu item "refresh" in the IDL Repository item in the Target SDR explorer.  This used to allow refreshing just the IDL Repository.  In RedHawk 2.0 it appears to do nothing, while right-click refresh on the Target SDR does refresh the IDL tree along with everything else.

**Comment by tandersoft** [comment]
The graphical editor for waveforms is much improved in RedHawk 2.0.  The connection lines are bolder.  Rather than routing them around other objects with square corners the connection lines go straight between ports.  This is unusual as most graphical editors DO route, but the previous (1.10 and before) did a poor job dealing with connections from right to left (ie. out port to an in port on a component to the left.  Over all this is better even though a little ugly, but it would be much nicer if in ports could be optionally placed on the right side and out ports optionally placed on the left rather than having no control of the side a port is placed on.  This could be done by either allowing ports to be dragged around to place them, or a boolean selection on the waveform wizard port add for right/left.  This would make diagrams for communications waveforms which usually have payload paths both left to right and right to left, look much nicer.

**Comment by drwille** [comment]
A fix has been applied to the develop-1.8, develop-1.9, and develop-1.10 branches, and has been released in version 2.0.1.
