### ISSUE TITLE
Service components cannot have data ports

### ISSUE THREAD

**Issue by tandersoft** [RedhawkSDR/eclipse-gov.redhawk.ide#6]
Service components built with the Service Project wizard do not appear to allow addition of any in or out ports for data.  Services in the SCA are often used for common services (shared by multiple SCA Applications or waveforms) that do not interface to hardware (where a device would be used). An example from the JTNC Standard Interfaces is Vocoder Service that encodes voice data using various codecs.  But this requires in and out ports with specific interfaces.  The wizard does not allow adding any ports.  I am not sure what kind of services can be implemented with this restriction.

**Comment by tandersoft** [comment]
BTW this issue is with version 1.10.0

**Comment by drwille** [comment]
See f5c4de538471f8da24c081573e305cb514e92247.

**Comment by tandersoft** [comment]
Thanks.  I did not see that change.  I will get 1.10.2 and test it.

**Comment by drwille** [comment]
The change is post-1.10.2, so unfortunately it hasn't been released in a built product yet.

**Comment by tandersoft** [comment]
Sorry.  Didn't understand your branch use.  It said it had been committed to the 1.10.2 branch but evidently that branch continued after the 1.10.2 release.  I'll watch for the next release and test it then.

**Comment by tandersoft** [comment]
The release notes for 1.10.2 include the item:
- Ports can now be added to Services that have an interface that inherits from CF::PortSupplier. 
Isn't this the fix?

**Comment by drwille** [comment]
Oops - you're correct. I must have been thinking about something else that wasn't included.

**Comment by tandersoft** [comment]
I installed 1.10.2 and tried it and WAS able to add a data port.  So although I have not tested actually building a service, it DOES appear fixed.
