### ISSUE TITLE
PyDev problem on Launch

### ISSUE THREAD

**Issue by ZachD47** [RedhawkSDR/eclipse-gov.redhawk.ide#8]
Upon launching Redhawk 1.10.2 I receive the following error message:

 "Problem Occurred: 'Configuring Python Environment' has encountered a problem. Failed to configure PyDev. Details >>> OSSIEHOME environment variable not defined, auto config fail.".

I am new to Redhawk and am unsure how to resolve this issue, any suggestions? Running on CentOS 6.6, issue occurred the very first time I launched the Redhawk IDE after completing installation following the Documentation. No problems were encountered during installation and omniORB was configured as suggested.

**Comment by tandersoft** [comment]
It would appear that OSSIEHOME is undefined in the Redhawks environment. Make sure that you are defining it and exporting it in the shell you use to launch Redhawk. I usually define it in .bashrc so it will be defined in all my shells or even if Redhawk is launched by a desktop icon.


Terry L AndersonTAndersoft
Sent from my mpbile phone

-------- Original message --------

**Comment by ZachD47** [comment]
Thanks for the advice, the issue is resolved now.

**Comment by ZachD47** [comment]
I must reopen this issue as it has occurred again, this time on a different machine running Ubuntu 14.04 LTS distribution. After following the installation documentation found in Appendix F of the REDHAWK manual for Ubuntu source builds, I am again receiving the exact same error message  as before upon launching the IDE. I have defined $OSSIEHOME in .bashrc (as the documentation details and you previously suggested) and the terminal recognizes the environment variable (typing "# cd  $OSSIEHOME" will bring me to the directory /var/lib/redhawk/core as it should). In CentOS 6.6 this seemed to resolve the issue but it is not the case in Ubuntu 14.04. Any ideas would be appreciated.

**Comment by tandersoft** [comment]
Make sure it is exported.  It can be defined in the shell but unless exported it is not available in subshells created from that shell.  You can check by using 
# env | grep OSSIESHOME
env will show only those variables exported to the environment and so available to subshells
And, of course, if you launch RH from an icon it will not see variables defined after the main screen was launched.  
I do not use Ubuntu so not sure of any other issues that might be different there.

**Comment by ZachD47** [comment]
Turns out the solution was simple; I made the silly mistake of running the installation as root user the whole time. Previously i was launching the IDE with my normal user account through an icon on desktop resulting in the error. When I run launch the IDE from terminal as root everything works fine. Thanks for the fast reply and assistance.
